# SPDX-FileCopyrightText: 2014 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = windows-x64
TARGETS = envPaths dllPath.bat
include $(TOP)/configure/RULES.ioc
